part:
    width: 70 # дефолтная ширина вертикальной части
    difference: 10 # расстояние между вертикальными частями
    is_scale: True # масштабировать ли части относительно друг друга

main:
    color: '#d0d0d0' # цвет вычислительной стойки
    stroke_color: '#000000'  # цвет рамки вычислительной стойки

block:
    height: 6 # высота вычислительного блока
    color: '#6a6a6a' # цвет блока
    stroke_color: '#000000' # цвет рамки блока

commutator:
    height: 2 # высота коммутатора
    colors:  # цвета коммутаторов разных типов
        type_1: '#3e73a2'
        type_2: '#6b3fa1'
    stroke_color: '#ffffff' # цвет рамки коммутатора

blade:
    height: 30 # высота блейд-шасси
    color: '#9e9e9e' # цвет блейд-шасси
    stroke_color: '#ffffff' # цвет рамки блейд-шасси
    servers:
        color: '#6a6a6a'  # цвет сервера в блейд-шасси
        stroke_color: '#ffffff'  # цвет рамки сервера в блейд-шасси